### ISSUE TITLE
Crashes related to slow request handling

### ISSUE THREAD

**Issue by lalinsky** [karlseguin/http.zig#82]
I'm using the 0.13 version of your library for a server component that could potentially take a long time to respond. However, I'm seeing crashes that seem to correlate with these slow requests. There was one case where it crashed inside httpz code during socket handoff. I unfortunately don't have the stacktrace for that. One, more recent case, was crash in my code, when trying to sort memory allocated on `req.arena`. It seems to indicate to me that something inside httpz would clear the arena while request was still working. Do you see that as realistic? It's unfortunately very hard to reproduce, only happens once I try to put live traffic on it and I can't really run it in debug mode like that. I see the the socket handling is changed significantly in the main branch, do you think this could be handled better there? I'm sorry for a vague bug report, but I'm running out of options to debug this, and I'd really like to continue using your lib, as it has a great API.

**Comment by karlseguin** [comment]
The master implementation is quite different, and I would be curious to know if the error happens there also, though I understand that all your other libraries might not be Zig-master compatible.

What OS?

Is the system under load?

Is it possible the client is sending a 2nd request while the 1st one is still processing, or disconnecting while the request is being processed. Both of these cases should be fine (and I just tried to trigger both cases on Mac and Linux using the zig-0.13, and they both behaved normally), but improper handling of either these cases would be the most likely cause for the arena being freed improperly.

Any chance for a reproducible case? I assume this is the repo: https://github.com/acoustid/acoustid-index/ ? What's the URL that's causing the issue and is there anything else I should try in order to trigger it (like hitting other URLs at the same time, etc).

**Comment by karlseguin** [comment]
0.13 will crash if `timeout.request` happens while the request is being processed. I see that you're setting a 60 second timeout and you mentioned slow requests, so I'm thinking this is the issue.

Setting `timeout.request = null` would solve the issue (and is recommended if you're running httpz behind a reverse proxy which is enforcing its own timeouts).

This isn't an issue in master.


If removing the timeout isn't an option, nor is using master, I can look at fixing this in the zig-0.13 branch.

**Comment by lalinsky** [comment]
Thank you for confirming that. I'll remove `timeout.request` and upgrade to the master branch later on. This is an internal service anyway, with a custom proxy in front of it, I don't need the server side timeouts anyway.

And thank you for this library! Really clean and easy to use API.
